<?php


mail(
    "somebody@mail.ru", # To
    "Mail robot",       # Subject
    "Hello!\nThis is autogenerated message - please do not replay."
);

mail(
    "somebody@mail.ru", # To
    "Mail robot",       # Subject
    "Hello!\nThis is autogenerated message - please do not replay.",
    join("\r\n", array( # Другие заголовки
        "From: webmaster@{$_SERVER['SERVER_NAME']}",
        "Reply-To: webmaster@{$_SERVER['SERVER_NAME']}",
        "X-Mailer: PHP/" . phpversion()
    ))
);

?>